'use strict';
const R=BeastRules,$=id=>document.getElementById(id);let state=R.initial(),history=[],selected=null,hintMove=null,timer=null,mode='easy',sound=false,audioContext=null;
try{const saved=JSON.parse(localStorage.getItem('beast-grove-v1'));if(saved&&Array.isArray(saved.state.pieces)&&['easy','normal','local'].includes(saved.mode)){state=saved.state;mode=saved.mode;history=saved.history||[];}}catch{}
$('mode').value=mode;
const sideName=s=>s===0?'蓝方':'橙方';
function save(){try{localStorage.setItem('beast-grove-v1',JSON.stringify({state,mode,history}));}catch{}}
function tone(win=false){if(!sound)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.setValueAtTime(win?660:440,audioContext.currentTime);o.frequency.exponentialRampToValueAtTime(win?990:600,audioContext.currentTime+.1);g.gain.setValueAtTime(.055,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.2);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.22);}catch{}}
function render(message){$('board').replaceChildren();const legal=selected?R.moves(state,selected):[];for(let y=0;y<R.H;y++)for(let x=0;x<R.W;x++){const p=R.at(state,x,y),move=legal.find(m=>m.x===x&&m.y===y),cell=document.createElement('button');cell.className='cell'+(R.water(x,y)?' water':'')+(R.camp(x,y)?' camp':'')+(R.den(0,x,y)||R.den(1,x,y)?' den':'')+(p?.id===selected?' selected':'')+(move?' legal':'')+(move?.capture?' capture':'')+(state.last?.to[0]===x&&state.last?.to[1]===y?' last':'')+(hintMove&&hintMove.x===x&&hintMove.y===y?' hinted':'');cell.dataset.x=x;cell.dataset.y=y;let terrain='';if(R.camp(x,y))terrain='✦<small>营地</small>';if(R.den(0,x,y))terrain='⌂<small>蓝方家</small>';if(R.den(1,x,y))terrain='⌂<small>橙方家</small>';cell.innerHTML='<span class="terrain">'+terrain+'</span>';if(p){const t=R.types[p.kind];cell.innerHTML+='<span class="piece '+(p.side===1?'orange-piece':'')+'"><span class="rank">'+t.rank+'</span><span class="emoji">'+t.emoji+'</span><span class="piece-name">'+t.name+'</span></span>'; }cell.setAttribute('aria-label',`${x+1}列${y+1}行${p?' '+sideName(p.side)+R.types[p.kind].name:''}${R.camp(x,y)?' 营地':''}${move?' 可移动':''}`);cell.onclick=()=>clickCell(x,y);$('board').append(cell);}
for(let side=0;side<2;side++)$(side===0?'blue-stars':'orange-stars').innerHTML=Array.from({length:5},(_,i)=>'<span class="'+(i<state.scores[side]?'filled':'')+'">★</span>').join('');$('blue-name').textContent=mode==='local'?'蓝方小队':'你 · 蓝方';$('orange-name').textContent=mode==='local'?'橙方小队':'小狐狸 · 橙方';$('round').textContent='第 '+(Math.floor(state.ply/2)+1)+' 回合';$('status').textContent=message||(state.winner!==null?state.reason:mode!=='local'&&state.turn===1?'小狐狸正在想下一步…':selected?R.types[state.pieces.find(p=>p.id===selected).kind].tip:state.ply===0?'点一只蓝方动物，向两侧金色营地出发。':sideName(state.turn)+'行动 · 点选动物，再点亮起的格子');$('undo').disabled=!history.length;$('hint').disabled=state.winner!==null||(mode!=='local'&&state.turn===1);$('log').replaceChildren();state.log.slice(0,5).forEach(t=>{const p=document.createElement('p');p.textContent=t;$('log').append(p);});}
function clickCell(x,y){if(state.winner!==null||(mode!=='local'&&state.turn===1))return;const m=selected?R.moves(state,selected).find(m=>m.x===x&&m.y===y):null;if(m){history.push(R.clone(state));play(m);return;}const p=R.at(state,x,y);hintMove=null;if(p?.side===state.turn){selected=selected===p.id?null:p.id;render();}else{render(p?'这只动物现在不能吃，试试其他路线。':'先选自己的动物，再点有圆点的格子。');}}
function play(m){state=R.apply(state,m);selected=null;hintMove=null;tone(state.winner!==null);save();render();if(state.winner!==null)showResult();else schedule();}
function schedule(){clearTimeout(timer);if(mode!=='local'&&state.turn===1&&state.winner===null)timer=setTimeout(()=>{const m=R.choose(state,mode);if(m)play(m);},650);}
function showResult(){$('result-title').textContent=state.winner===-1?'势均力敌的一局':mode==='local'?sideName(state.winner)+'赢啦！':state.winner===0?'这片森林，你说了算！':'小狐狸这次略胜一筹';$('result-icon').textContent=state.winner===0?'🏆':state.winner===-1?'🤝':'🦊';$('result-reason').textContent=state.reason;$('result-score').textContent='蓝方 '+state.scores[0]+' ★  :  '+state.scores[1]+' ★ 橙方';if(!$('result').open)$('result').showModal();}
function restart(){clearTimeout(timer);state=R.initial();history=[];selected=null;hintMove=null;$('result').close();save();render();}
$('undo').onclick=()=>{if(!history.length)return;clearTimeout(timer);state=history.pop();selected=null;hintMove=null;$('result').close();save();render('退回刚才的选择，再试一条路。');};$('restart').onclick=restart;$('again').onclick=restart;$('review').onclick=()=>$('result').close();$('mode').onchange=e=>{mode=e.target.value;restart();};$('hint').onclick=()=>{hintMove=R.choose(state,'normal');if(!hintMove)return;selected=hintMove.id;render('试试这一步：亮起的金框是建议落点。');};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♪ 有声':'♪ 静音';$('sound').setAttribute('aria-label',sound?'关闭音效':'开启音效');tone();};$('rules').onclick=()=>$('help').showModal();$('close-help').onclick=()=>{$('help').close();schedule();};$('start').onclick=()=>{$('help').close();schedule();};$('help').addEventListener('close',schedule);
for(const t of Object.values(R.types)){const row=document.createElement('div');row.className='animal-row';row.innerHTML='<div class="animal-icon">'+t.emoji+'</div><div><b>'+t.name+' · '+t.rank+'</b><p>'+t.tip+'</p></div>';$('animals').append(row);}render();schedule();
